[fruit and vegetables]
Chinese cabbage
apple
apples
aubergine
avocado
avocados
baby potato
baby tomatoes
bananas
bay leaf
beetroots
bell pepper
green pepper
bell peppers
lemongrass
lime leaves
blueberries
broccoli
butternut
carrot
carrots
cauliflower
celeriac
celery
cherry tomatoes
clementine
coconut
coriander
courgettes
cucumber
dill
fresh basil
fresh oregano
garlic
garlic clove
ginger
grapes
kale
leeks
lemon
lime
mango
melon
mushrooms
nectarines
onion
onions
parsley
pawpaw
peaches
pears
potatoes
raspberries
red chilli
red onion
red onions
red peppers
rosemary
salad leaves
scallions
shallot
shallots
sugar snap peas
spinach
spring onions
strawberries
thyme
tomato
tomatoes
baby corn



[meats]
bacon
chicken thighs
chicken fillets
corn beef
lamb chops
parma ham
rashers
lamb
prawns
smoked salmon
whole chicken
anchovy
beef mince
organic whole chicken
sirloin steak
chorizo

[eggs and dairy]
butter
cheddar cheese
curd cheese
egg
eggs
feta
feta cheese
full cream plain cottage cheese
grated mozzarella
hard cheese
milk
mozzarella
soft cheese
sour cream

[bakery]
Woolworths Berliner Landbrot Bread
Woolworths Cape Seed Bread
apple lattice pie
biscuites with hearts
bread
breadcrumbs
breakfast biscuites
croissant
profiteroles
tortillas

[pantry]
Chinese cooking wine
Dijon mustard
Marmite
apple crisps
baked beans
balsamic glaze
bay leaves
beef stock
chicken stock
black pepper
black tea
canned tomatoes
cannellini beans
caster sugar
cayenne pepper
chicken broth
chickpeas
chilli flakes
chilli oil
choclate bars
chopped tomato
cider
cloves
coffee
cooked rice
rice
rolled oats
corn starch
crackers
crisps
dates
dijon mustard
dried apricotes
dried oregano
dried plums
dried sage
extra virgin olive oil
fennel seeds
flaky salt
flour
fresh yeast
frozen peas
fusilini pasta
garlic powder
ground cinnamon
ground coriander
ground cumin
honey
kalamata olives
linguine pasta
mayonnaise
oats
oil
olive oil
onion powder
oyster sauce
paprika
pasta
peanut oil
pepper
pepper corns
pickled jalapeno
pickles
pistachio
plain flour
poultry seasoning
pumkin seeds
pumpkin seeds
raisins
red wine
red wine vinegar
redcurrant jelly
rice wine vinegar
rooibos tea
salt
sea salt
sesame oil
smoked paprika
soy sauce
star anise
strained kimchi
strong white flour
sugar
tahini
tin tomatoes
tinned pineapples
tomato paste
vegetable stock
water
white beans
white pepper
white vinegar
white wine
chia seeds
cinnamon
coconut milk
nut butter
plant-based milk
Thai green curry paste
vinegar
